### ISSUE TITLE
可以更新成替换全部模型的吗?

### ISSUE THREAD

**Issue by YuricaKirisame** [gordonwalkedby/CSGOUIx#1]
我是小白,每次用notepad++逐个替换太麻烦了,请问可以更新替换全部模型的吗?

谢谢.

**Comment by gordonwalkedby** [comment]
（（
啊啊啊，（头像好可爱）
这个
我真的很不想再重新去看这个代码了 ;w;  我本来是打算结束这个软件的维护或者更新的

**Comment by gordonwalkedby** [comment]
;w;还有就是，和 Notepad++ 有什么关系吗？（（
你平时是怎么操作这个软件的？

**Comment by YuricaKirisame** [comment]
https://steamcommunity.com/sharedfiles/filedetails/?id=1419995135

我是看着这个指南做的,只是用notepad++改.

**Comment by gordonwalkedby** [comment]
((
那个指南和我这个软件好像关系不大
你是怎么到我这里来的呢
我这个软件也能替换，虽然只能一次替换一个，但是只需要按数字就好了（（（

**Comment by YuricaKirisame** [comment]
嗯,所以我的意思是希望软件可以有更多的原版人物可供修改.(类似一次改完5个sas人物那种,而不是单独一个sas)

**Comment by gordonwalkedby** [comment]
（我觉得不行，我不想再碰这个老软件的代码了）））））））））

**Comment by gordonwalkedby** [comment]
还是去别的地方看看吧（
